version: "3"

services:
  postgres:
    image: "postgres:14"
    volumes:
      - ./init-scripts/postgres:/docker-entrypoint-initdb.d/
    environment:
      - "POSTGRES_USER=nestjs_query"
      - "POSTGRES_HOST_AUTH_METHOD=trust"
    expose:
      - "5432"
    ports:
      - "5436:5432"

  mysql:
    platform: linux/x86_64
    image: "mysql:8"
    volumes:
      - ./init-scripts/mysql:/docker-entrypoint-initdb.d/
    environment:
      - "MYSQL_USER=nestjs_query"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
    expose:
      - "3306"
    ports:
      - "3306:3306"
  redis:
    image: "redis:6"
    ports:
      - "6379:6379"

  mongo:
    image: "mongo:5.0"
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./init/-scripts/mongodb/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  mongo-express:
    image: "mongo-express:latest"
    restart: always
    ports:
      - 8081:8081

