version: "3"

services:
  db1:
    image: "postgres:11.5"
    environment:
      - "POSTGRES_USER=graphqltypeorm_mdb1"
      - "POSTGRES_DB=graphql_typeorm_mdb1"
    expose:
      - "5432"
    ports:
      - "5437:5432"
  db2:
    image: "postgres:11.5"
    environment:
      - "POSTGRES_USER=graphqltypeorm_mdb2"
      - "POSTGRES_DB=graphql_typeorm_mdb2"
    expose:
      - "5432"
    ports:
      - "5438:5432"
